src/main.rs

Unfortunately, I made one mistake in #10 pull request. :sweat_smile:

Fix `walk_dir` return value (really closes #1)

---

src/main.rs

Old error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
```
New error:
```
Could not find directory "target/doc/svgcleaner".
Please run `cargo doc` before running `cargo deadlinks`.
```

feat(error): improve error message for missing target doc directory

---

src/parse.rs

This fixes a compilation error:
```text
error[E0509]: cannot move out of type `html5ever::rcdom::RcDom`, which implements the `Drop` trait
--> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-deadlinks-0.4.1/src/parse.rs:19:19
|
19 |     parse_a_hrefs(dom.document, &base_url, &mut urls);
|                   ^^^^^^^^^^^^ cannot move out of here
```
Also, can we get a release after this lands? :)

Fix compilation error.

---

.github/workflows/ci.yml
src/check.rs
src/lib.rs
src/main.rs

Shamelessly copied from https://github.com/rust-lang/docs.rs/blob/master/.github/workflows/ci.yml. Closes https://github.com/deadlinks/cargo-deadlinks/issues/61. Makes https://github.com/deadlinks/cargo-deadlinks/issues/26 a lot easier, but doesn't add pre-built binaries yet.
r? @kixiron

Add continuous integration

---

src/check.rs

Are there any downsides to use HEAD?
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html:
> This method is often used for testing hypertext links for validity, accessibility, and recent modification.

Use http HEAD method request instead of GET

---

src/main.rs
tests/simple_project.rs

This fixes one of the problems mentioned in https://github.com/deadlinks/cargo-deadlinks/issues/38, but not the other - `cargo metadata` doesn't take `CARGO_BUILD_DIR` into account either. IMO that should be an upstream cargo fix (https://github.com/rust-lang/cargo/issues/8791).

Take CARGO_TARGET_DIR into account

---

CHANGELOG.md
src/main.rs
tests/simple_project.rs

Closes https://github.com/deadlinks/cargo-deadlinks/issues/54

Give a better error message if Cargo.toml is not present

---

tests/non_existent_http_link/Cargo.toml
tests/working_http_check/Cargo.toml

These would cause spurious failures like
````
---- working_http_check::works stdout ----
thread 'working_http_check::works' panicked at 'Unexpected failure.
code-1
stderr=```Found invalid urls in /home/joshua/.local/lib/cargo/target/doc/simple_project/fn.foo.html:
Error fetching http://thiswebsitedoesnotexist.xyz/: error sending request for url (http://thiswebsitedoesnotexist.xyz/): error trying to connect: dns error: failed to lookup address information: Name or service not known
```
command=`"/home/joshua/.local/lib/cargo/target/debug/cargo-deadlinks" "deadlinks" "--check-http"`
code=1
stdout=``````
stderr=```Found invalid urls in /home/joshua/.local/lib/cargo/target/doc/simple_project/fn.foo.html:
Error fetching http://thiswebsitedoesnotexist.xyz/: error sending request for url …

Fix test collisions when using a shared CARGO_TARGET_DIR

---

CHANGELOG.md
src/main.rs
tests/renamed_package/Cargo.toml
tests/renamed_package/src/main.rs
tests/simple_project.rs

Closes https://github.com/deadlinks/cargo-deadlinks/issues/21.
Targets are not unique within a package, so this required checking all applicable targets.

Follow target renames

---

src/main.rs
tests/renamed_package/Cargo.toml
tests/simple_project.rs

This fixes a regression introduced in https://github.com/deadlinks/cargo-deadlinks/pull/68 and adds a test.

Fix packages with dashes instead of underscores

---

CHANGELOG.md
src/main.rs
tests/simple_project.rs
tests/workspace/Cargo.toml
tests/workspace/a/Cargo.toml
tests/workspace/a/src/lib.rs
tests/workspace/b/Cargo.toml
tests/workspace/b/src/lib.rs

- Add a test for workspaces
This was implemented in https://github.com/deadlinks/cargo-deadlinks/pull/68,
although I didn't realize it at the time.
- Don't try to document benches, examples, and tests
`cargo doc` does not document these targets, so there will be no
corresponding doc directory.
- Don't exit on the first target that fails; instead check all targets.
Closes https://github.com/deadlinks/cargo-deadlinks/issues/9.

Various bugfixes and tests

---

Cargo.toml

This doesn't yet update cargo_metadata because it added 8 more
dependencies since 0.9.

Update some more dependencies

---

CHANGELOG.md
src/main.rs

@martin-t can you confirm that this fixes your issue with non-deterministic output? I can't reproduce your issue locally.
Hopefully closes https://github.com/deadlinks/cargo-deadlinks/issues/56.

Always output all errors instead of stopping after the first error

---

src/lib.rs
src/main.rs
tests/simple_project.rs
tests/simple_project/src/lib.rs

Closes https://github.com/deadlinks/cargo-deadlinks/issues/19.
I did a bit more, now the output looks like
> struct.InlineString.html: Linked file primitive.char.html does not exist!
> struct.InlineString.html: Linked file iter/trait.DoubleEndedIterator.html does not exist!
> struct.InlineString.html: Linked file primitive.char.html does not exist!
> struct.InlineString.html: Linked file iter/trait.DoubleEndedIterator.html does not exist!
> struct.InlineString.html: Linked file primitive.char.html does not exist!
> struct.InlineString.html: Linked file primitive.char.html does not exist!
> struct.InlineString.html: Linked file primitive.char.html does not exist!
> struct.InlineString.html: Linked file primitive.char.html does not exist!
> struct.InlineString.html: Linked file …

Improve display of findings

---

Cargo.toml

That's right, no code changes needed!
Closes https://github.com/deadlinks/cargo-deadlinks/issues/31.

Switch to 2018 edition

---

CHANGELOG.md
src/check.rs
tests/html/index.html

When providing links it is common to abbreviate `path/to/index.html` as
`path/to/`, i.e. to omit `index.html`. This change refines the check to
take that case into consideration: a path to be considered valid, needs
to point to a _file_ or to a _directory containing index.html_.
Existing check would check if a path exists, regardless of if that path
was pointing to a directory or to a file.

feat: allow for index.html expansion

---

CHANGELOG.md
src/parse.rs

Some `href` values might start with a `/`, denoting an absolute path and
should be considered relative to the given `dir` path. In `url::Url`
`join`-ing absolute path results in that absolute path, i.e.:
```
assert!(base.join(Url::from_file_path("/page.html").unwrap()) == "/page.html")
```
In this case deadlinks would flag `/page.html` to be broken, whereas it
could be considered valid relative to the `base` path.

feat: handle absolute paths

---

src/lib.rs
src/parse.rs

I'm afraid a bug was introduced in #91: Absolute paths should be rooted from the `--dir` path, not against the base directory of the examined file. For example, given file in `$DIR/sub/a.html` with a link to `/other/b.html` and deadlinks invoked with `--dir $DIR`, that link should be evaluated as `$DIR/other/b.html`, not as `$DIR/sub/other/b.html`.

fix: correctly treat absolute paths against `dir`

---

Cargo.lock
Cargo.toml

It was unused. This removes a serde_json dependency.
This also bumps the version requirement for ureq to 1.5.2, since it won't compile in earlier versions.

Remove `cookies` dependency for ureq

---

CHANGELOG.md
src/main.rs

This also greatly simplifies the code by using `MetadataCommand::exec`
instead of rewriting it.
Closes https://github.com/deadlinks/cargo-deadlinks/issues/97.

Don't download dependencies from crates.io

---

CHANGELOG.md
src/main.rs
tests/simple_project.rs

- Read `RUST_LOG`. Previously it was ignored.
- Print errors to stdout, not stderr. Don't go through `log` for errors.
- Don't override the logging format for `info` and `debug` level logging.
- Mark `--debug` and `--verbose` as deprecated
Closes https://github.com/deadlinks/cargo-deadlinks/issues/92.

Improve handling of logging

---

.github/workflows/deploy.yml
CHANGELOG.md
Cargo.toml
src/bin/cargo-deadlinks.rs
src/bin/deadlinks.rs
src/bin/shared.rs
src/check.rs
src/lib.rs

- Expose public `walk_dir` function, which prints all missing files
- `impl Clone for CheckContext`
- Put cargo dependencies behind a feature gate
- Switch from `Into` to `From` to help type inference
Closes #47.
r? @hobofan - what do you think? Does it make sense to expose `walk_dir` publicly? If not, I can move it into `mod shared`.

Split cargo-deadlinks and deadlinks into two binaries

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/check.rs
src/lib.rs
src/parse.rs
tests/html/anchors.html
tests/html/range.html

_Note: I'm fairly certain that this can be polished, please consider the direction of the implementation first. I'm happy include any suggestions. I appreciate the time it takes to review this largish PR. Thanks!_
_Update: rebased and changed to check fragments in HTTP URLs_
This implements URL fragment checking. Parsing is expanded to also
collect values of all `id` attributes.
For missing fragments in files a `CheckError::Anchor` will be returned
containing a path and the missing fragment.
In Rust documentation non-existent fragments in the form of `#n-m` is
used to highlight a range of lines in the source code. For fragments in
that form additional check is performed to test if all fragments `n`
through `m` exist. In case of missing items in a ranged fragment
`CheckError::AnchorRange` …

feat: check URL fragments

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/bin/cargo-deadlinks.rs
tests/broken_links.rs
tests/broken_links/Cargo.toml
tests/broken_links/src/lib.rs
tests/simple_project.rs

Closes https://github.com/deadlinks/cargo-deadlinks/issues/11, fixes https://github.com/deadlinks/cargo-deadlinks/issues/38 as long as you don't pass `--no-build`, fixes https://github.com/deadlinks/cargo-deadlinks/issues/99 as long as you don't pass `--no-build`.
TODO: add better tests that can tell whether the documentation was rebuilt with `CARGO_TARGET_DIR` set, otherwise it will definitely regress.

Build documentation if not already built

---

src/check.rs

@jyn514 this is a simple touch up to fragment checking, something I find commonly used, not sure about rustdoc, in general though it will be helpful especially with the standalone usage.
Empty fragments, such as `.../file.html#` are valid fragments indicating
the top of the document. See[1]
[1] https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-fragid

chore: handle empty fragments

---

CHANGELOG.md
src/bin/cargo-deadlinks.rs
src/bin/deadlinks.rs
src/check.rs
src/lib.rs

This adds `--ignore-fragments` parameter to the command line, when
specified no fragment checking will be performed.
@jyn514, this is my first quick pass at this, happy to incorporate any suggestions you might have.

feat: --ignore-fragments CLI parameter

---

CHANGELOG.md
src/bin/cargo-deadlinks.rs

Hopefully fixes https://github.com/deadlinks/cargo-deadlinks/issues/119, waiting on someone with a windows machine to test.

Don't assume `/` is the directory separator

---

tests/non_existent_http_link/src/lib.rs

On ISPs that 'helpfully' redirect requests to a website with a
non-existent DNS, the test would previously fail, since the page
returned 200, not 404. Use a non-existent page on example.com instead,
which should hopefully be more resilient to malicious/unthinking actors.

Use 404 pages on example.com instead of a non-existent DNS

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/bin/cargo-deadlinks.rs
src/bin/deadlinks.rs
src/bin/shared.rs
tests/broken_links/hardcoded-target/index.html
tests/cli_args/Cargo.toml
tests/cli_args/src/lib.rs
tests/simple_project.rs
tests/simple_project/src/lib.rs

See the changelog for everything this changes.
https://github.com/RazrFalcon/pico-args/issues/25 would have made this a lot easier.
Closes https://github.com/deadlinks/cargo-deadlinks/issues/115. Fixes https://github.com/deadlinks/cargo-deadlinks/issues/111. Fixes https://github.com/deadlinks/cargo-deadlinks/issues/89.
~~This will unfortunately be a breaking change *specifically* because of the change to `walk_dir`. In practice I doubt anyone was using it, but better safe than sorry.~~ I'm going to make this change in a follow-up to avoid having to release a new major version: https://github.com/deadlinks/cargo-deadlinks/issues/117

Switch to pico-args

---

CHANGELOG.md
src/bin/cargo-deadlinks.rs
src/bin/deadlinks.rs
src/lib.rs

Closes #117.
This is a breaking change and should wait until https://github.com/deadlinks/cargo-deadlinks/pull/116 is merged I think.

CheckContext -> &CheckContext

---

CHANGELOG.md
src/check.rs
src/lib.rs
tests/broken_links.rs
tests/broken_links/src/lib.rs

Closes https://github.com/deadlinks/cargo-deadlinks/issues/125.

Shorten fragment errors

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib.rs
tests/working_http_check/src/lib.rs

Closes https://github.com/deadlinks/cargo-deadlinks/issues/110.

Update ureq, handling 307/308 redirects

---

CHANGELOG.md
Cargo.lock
Cargo.toml

The only change in this release is to follow HTML `<meta>` redirects.

Release 0.7.1

---

LICENSE-APACHE

I've been copy-pasting around a wrong license file that has an unnecessary part at the end that ends mid-sentence in the past. This one is identical to the one in the Rust repository.

Fix Apache license text

---

CHANGELOG.md
src/check.rs

Example output:
```
$ RUST_LOG=warn cargo deadlinks
[2021-01-08T15:21:18Z WARN  cargo_deadlinks::check] Skip checking http://example.com/ as checking of http URLs is turned off
[2021-01-08T15:21:18Z WARN  cargo_deadlinks::check] Skip checking https://play.rust-lang.org/ as checking of http URLs is turned off
[2021-01-08T15:21:18Z WARN  cargo_deadlinks::check] Skip checking
https://tinyurl.com/rnxcavf as checking of http URLs is turned off
```
@hobofan is this what you were imagining for https://github.com/deadlinks/cargo-deadlinks/issues/44 ? Or did you want it to be an unconditional warning? I kind of like that it's opt-in, but I could be convinced otherwise.
Closes #44

Promote 'skip checking' message to a warning

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/check.rs
tests/non_existent_http_link.rs

Congrats to @jsha and @algestan on the release :tada: The new code is shorter and even gets rid of a dependency :)
This is a breaking change since deadlinks has `ureq::Transport` in the public API.

Switch to ureq 2.0

---

tests/simple_project.rs

Make the test independent from the directory in which the repository is checked out.
Fixes #148

Fix simple_project test when top-level directory is not named `cargo-deadlinks`

---

tests/simple_project.rs

I maintain the `cargo-deadlinks` package for NixOS; and as part of the packaging the tests get run to ensure the correct linkage.  This tests adds an ignore flag for the `it_checks_okay_project_correctly` test when the target is not `x86_64-unknown-linux-gnu`, which allows the tests to be run on other architectures.

add TARGET env var to select target for tests

---

Cargo.lock
Cargo.toml
src/bin/cargo-deadlinks.rs
src/lib.rs
tests/non_existent_http_link.rs
tests/working_http_check.rs

Fixes https://github.com/deadlinks/cargo-deadlinks/issues/155
```
; cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 470 security advisories (from /home/jnelson/.local/lib/cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (146 crate dependencies)
Crate:     regex
Version:   1.5.4
Title:     Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:      2022-03-08
ID:        RUSTSEC-2022-0013
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution:  Upgrade to >=1.5.5
Dependency tree:
regex 1.5.4
├── predicates 2.0.3
│   ├── cargo-deadlinks 0.8.1
│   └── assert_cmd 2.0.2
│       └── cargo-deadlinks 0.8.1
├── mockito 0.30.0
│   └── cargo-deadlinks 0.8.1
├── …
```

Update insecure dependencies
